name: "slack-notification-action"
description: "send slack notifications with hooks"
inputs:
  slack-webhook-url:
    description: 'slack webhook url'
    required: true
  slack-message:
    description: 'slack messgae to send'
    required: true
runs:
  using: 'composite'
  steps:
    - run: curl -X POST -H "Content-Type:application/json" --data '{"text":"${{ inputs.slack-message }}"}' ${{ inputs.slack-webhook-url }}